#!/usr/bin/env bash
set -euo pipefail
cd /opt/ai-stock-combo

set -a
[ -f /opt/hermes-data/.env ] && . /opt/hermes-data/.env
set +a

export TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID:-${TELEGRAM_HOME_CHANNEL:-}}"
export PYTHONUNBUFFERED=1
export PIPELINE_OPENBB_TIMEOUT="${PIPELINE_OPENBB_TIMEOUT:-360}"
export PIPELINE_OPENBB_WORKERS="${PIPELINE_OPENBB_WORKERS:-8}"
export PIPELINE_TRADINGAGENTS_FULL_N="${PIPELINE_TRADINGAGENTS_FULL_N:-10}"
export PIPELINE_TRADINGAGENTS_WORKERS="${PIPELINE_TRADINGAGENTS_WORKERS:-2}"
export PIPELINE_TRADINGAGENTS_FULL_TIMEOUT_PER_STOCK="${PIPELINE_TRADINGAGENTS_FULL_TIMEOUT_PER_STOCK:-1800}"
export PIPELINE_UZI_TIMEOUT_PER_STOCK="${PIPELINE_UZI_TIMEOUT_PER_STOCK:-240}"
export PIPELINE_UZI_TIMEOUT_HARD_CAP="${PIPELINE_UZI_TIMEOUT_HARD_CAP:-260}"

mkdir -p outputs work
python3 run_daily_pipeline.py "$@"
